language: node_js
node_js:
  - "6"
install:
- npm install
script:
- npm run-script build
deploy:
  provider: npm
  skip_cleanup: true
  email: rafalnowosielski@me.com
  api_key:
    secure: "z9s7FLNi4BEz/oTAHwBk572xd4Pm1ZPK0wKTJT6O7Y/YAVDo+WjStVsouE9bcPzB0yXi7BStSH7lu9iGkVG4XnXB8D/V8AGwP5xk/0Tuv1grAKRndLcPjyc3SbN7QyABHh7+rdBzizFxr8Ps54h0F04sDMG7wewfAa7G4Jv+bQtV4MdrccwYS5Enyssd+KR4MLJdhdh5afj6ENyEG8aZ3tD+qurd+FZTNwO6vifQaLoL5uX2UjO/RDQJEla5bwGKseJwJxkls1AnSfEzb6gLF0hErppAauvFYzgDtUdon/2KocDAaE0fKrx0ZKGDo+l3VUo0TXnngxTv85JhRV4kz6lrQuTUn2O9aNmfQtyaxfWf2jxxrYCNKTUySsZRC24tr9QnJudKUxJ5pGUl+B2dTvYgaFzIe6s08VR85HN0ZRHFsMJAMpzjD3UULxBBgVB851Gp/iPi7SPuxvmudpNlLDXDaLmM88ClHDNHqG8UWI87FvlO+zwFn02udqafBhMX1q8wwTuWyIc4Ryt3HIN86Qqkt4VYwZVUssu9olwYD9wubYEy+naY/n7eMxqhzi6S0Ne3YNI6O/XWt9r0RGVbEq+ipxi3pUMtJzteA+avFGgZX1Q05CIfyyFltMzMHvSyHqOFTVCTqyffoxrD4E7foN1aWwdISQNdWlUKFwxVCVg="
  on:
    branch: master
notifications:
  slack:
    secure: "RvaxJY/sKUlHj8F4vazDjcUrUItXEZhz2XAABFUqkfaK9d9wTincfLgqdBzZFndKoCDYajHdWWYCs1dhRCSwgZ6K5Co6wJKWYY6iC67YW0NOmO2m5MHLt9OQgbfGaD5gTKdlJblII2RGxzskkWsMR1IEypMKCm5IkgWmHeaK/0LXs36p+8VGgkBY3Rehd55T0IjkBXqJ+jFJmH9n149tT+BHnYjTeIWC3W+Us+2ydnYljmhXovFwz8MuXMD+GWnOtXOFrbVxX1XPc7mZJnTH6X/8fzbZZbnAsUPhAxN1kLk4jrUTAKkGdUuqlr81xUe0vHrML0JYjwhPirHu4AipIJ1U6l9GmcG/sd9LlPbUxuQkBygv39gcVHDAIAbEO6s8gOB22J2yENWINJfHNnEq0Ncd4vavI8VdAC+TRs8UkU1sPRDjwgI54rsf3oo/IqRdj7x+nERFaoKF6Q6LJ0BzoLzYu/19AveR2D25zLWDCPV4JH7y12FW0wqr8cPd+RQ0o13Atyqy3q0lAlJ5Ey+hDQAH/Qj7Lr7BQ3TODBYnwz3cD/hW8nUzXbDIo0knHBHBltsmhrvOHJC2z/OmOyf/QkQBblxv6PRFYuSjsg9P7HumfEf8Vh2nAAEu1yLdTOFwAX7Os/Sty5hQLAqjyi/lUxKDlW0h2ZFJI0BjnTuMPMw="
