language: node_js
node_js:
- '8'
dist: trusty
sudo: false
addons:
  chrome: stable
branches:
  except:
  - results
install:
- npm install
script:
- npm run translate
- npm run check
- npm run storybook
- sleep 20 && echo "done waiting"
- node_modules/.bin/backstop test
- npm run-script build
after_script:
- "./push.sh"
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  skip_cleanup: true
  api_key:
    secure: S0zxXNHUhGg6uEsi5Cffflr0m5tJyMgXTZBUR39EAtTWCNhPGCLmUFoOjNW6gkEFpRt+fTqmAfI0FJ7VZZSQxZniCEiRjjDtxr3Lur8wg/dKef9BzxhLZcZX5eegPB2K0VMebMFWXDUMJWLiiN4HiGfBK7dHvymmAXoQOfIXbPgonSK9JBkDNsZ0QDN5GorLX7GCSO44J2xIUMzHUIlq1DTIeVMe3TLC1KXs3RG4flkwjgetkht1AeqHQ2HHEAzN7i2q/Djcpnzco3QRwe3XXS9eSnMTUW1u0uGf5RwO7wT5Ci2OaKzod4TvEXw1JYvj2r+jfhZyJdLMSvKgseWKfqCX5e/f9NA77mSUvU/dzkdegiUUO34YCAlBYS/A/wkSMaX708Di1/8ZpHvEiewZ4DK5MKcgDQ1+yL3Jo2luuRy5to+/wjzHr6zsLLWjIrAYTkICMue5Xqemg/GrYsxYYQeRGd4Dhjrxg2f2UB8DhyRvLCu5raHwj3fBusUCKnzFIKBLDccnjfWu7NKcRCiTNN+ZWHXaHYB//iX/FO8EWLYXYOYJ6y7RHYzJyUBo2gf2FdbYmOmtKCYWN0xec2XhjBZhk1HYkNyt3oBzxNLydR6tnnNtNy7Kvz4ovMDBXx+qSXQLhhVS3W5ntPvMifs8AAr+1zqSAin4aHi5EuReFGc=
  on:
    branch: master
notifications:
  slack:
    secure: hcLcEUCHCua4mqVMhP1vXIsxaSJ9/u30xGIswPPg9iNdraL6V0CGbO9AUddP+Wpr+UEOxFhqA8aknZ6U0uDFg3Mi5h/IWerLSbFaJzuQtqoVWQuHFVkO4KgCRZy7Ihsk1U3e/JhsZIndmZ7/sMuN47K1naoEvahcbm7FrH8o7rUIFMrmHsGB7yIXtdbVcJINC8Ii5EN95ncGE3zOwVOBd5XMq8RYvxQWDEoyHxewJ3pkYW88Gss9Zjvs3SlOs3cq4jZyaB75DSHIZ1eeZ0A25/RANBdNH8BJcjtg4bMXk6KdG1t/9sn+KuHBU2EOwCIdRCzuuh2JXDA0wXh6oB7HDL484Kgq/rV/slEAVQXULMU/08txtZuf6DFDkVAB2E94SjzIWYUiOgzmbjEDbxs5SyuUJLu3Ciqua3Zpg2nDRQ4mvsOsAKW8CZxOapnM+29LlbNA4H0cfSrajLPwSt9LeWilFvoFvJ9KqfIzYDSxdoZFCMGfTOW9rlPL3zRWRYmn1rlQdCAoh751+wfvIXN5uU9sLWFBGt2jWqor0Lg4XtvFVGWCLtzfI0zh8aaBGihIVtsTCKeIC5mtFj6d83W+T4+WuV4niHnp2Xch9fVMLWThl+XuIDYRhG6cSrN8wmOZR+w6XJELBuzPhJ1qNGKxHJ9J5kgN5f04EUmTCvDmSVg=
env:
  global:
  - secure: R4sbWJmvaFSvehd0bjDtL7v5PrYLWqDdI2UVdjFlI/1ruAktJWbJ6fP42FF3vM9wJ5asQvmGAIxFkS+sl5N4AnLUxifIMvl4WpSY01oTCY5hmj/wHmYXeVKCHnx7lWwm0mHSeV0MWBbgS7AlFnhTD5fb6L9kbGKmVU8Q6vZk/ADHysWp6xXZ1D+uR+cmVbkhyPlgBlMNbFzMMjyVvbBBq3N5FK97Y7XuIC0V+VUlW+WoIu5IL5AnVVfq068w29XQeFOc7vPDP47Z9pYnH62PIu+oHzM4E0acZwideeANo7/0I6DQHtWrRoJj9b6K4j0QLTmZNjmyl2YjU241qcj2+wOzZrBZNgCbBW6io2Khf3kKMVEVhiWJ1Y7XG0mNXNv56KFazdXAa5qCDM4O9j0WX6Vg08mv3cVO1HHAKM9mo+NgYrUZaEYY4zvFrjP5BGY1rcfwq2yamf+DJXaQc9vZpktIYK8S6P5P/0o7IVVzLlN8Nf8p04OSCTO8KYmwaAta0CU4/W9JXHqOvJPmkYpjod47U6C82/0BA5sCw8GbTC2PDZRWA0Vss0QeiEGeRyoxBmxGkOFljCd7ix4a3cY+GGvRSj2sLRTzW8bHsvO60dKYiPoCdvUz8Gqvp33MgWvtsjyr+3d1rA6NYUlrlYWKtymQmpyyGX69VsEZAQ3IP58=
  - secure: w+uFPsGwJS/T67qa6xoAvhbwDQDOgnWhfn8+e8hLIPrKroUrpqM9OkSyNuiY0UzfQCPp4F1MF8ZqSj7FTa6BGtZfO8mVyhguD9GVM/ipZRXhP3t8z0lgj5eNCQRBXCslF8Pk/CZWGjXl32Yl2ClDBqM5cc+rbqpez7z01S/jd7onbn9qKdmtMVaB1YWwlGe6jAAjAX+oFhAs78kHQtxvs0YEV8OUoa+kIe3BRU0Qg3E8qhUijrSb28tmhFqCVxz47+8YbkEmnAPNDN/+Wjhvs5uhdlfARx26EMH7hKfm/qLgq9j8DIF8fhzc/7bU00xZ1Sq13yZ+NOJxm8KZs7pBeu0mEwftlYJzAdNpPPYhPqhKp9E6c23oTgP7bphOcyjlLHCzdmeaw119YW8DMj5B4oy7DFy8PFNWx12BwnHBJhKEKd1O7ODHOuQISXLdetu3FyASDgsCPwJRhFU/pqR7lpK4VioGHpO4YONcjkT99WI/heWM5bEgAVNw342coXQO69lg0QMbMv0zIJN81bn33AwCarVbRW4y37+u+gL7XA8aim28zLsZnh6/0c1KLgJ1pj2y0+NrSsb5p+xPftKPfSoZ6ARpHpAxfl+qa47or5g+auKRoUOe0Jcp0w9TH+UolDqdAFHKZ+TRzsfBm49QWxZ2tJltDP1XiX/q4uQyTBo=
  - secure: ibgn0UrhQltOUihhohlSLh32xpwk9i/2yDHKyVoHhaB1h1eS8zVL1INLx7yLgxe+o8Sxq8kRHHgA9BoYRzdUq+KXKCkqgOAcc3Ssy+tgRbyDGc3jqNqUqN312MWFxVPz+t8XSYeNypdlQ68CcaP0KFAEigqWZ5GjQmKF17qSC4ciihvi0blBH5qCntNTUuZu0PuqllZlq9DedhzQIwEp4Y84z3zdt1FimHvovHMNQPMZInsocKN1XaTqWweniy0/GQLUyQgauQZATgF0A7of/rkRldssmNQ2T766+u9otjYp/SJritzuuyR36rsPFXu8t8lrEl7/DUOyy/OzY3kkM/kFcVv0a7YVHSnJKFGviYEHgB6u2ITTT7gGXhmeNizPHIbpdHZ3T6gj66mE3xucneXaZpMFLlJ0plcl20LkS1V1tY+SMv8z+Wc1YhYVitQdlXdRFt7tpUDY1Exucisuh/eADIraBgs90a4W5a/MVpWQGUoWGY6y0Hn+njrIG6eY8d6jq/n1J6Zb4EpyWRxTuToTRERTRLg5E6KgAIKV7XbRv/U8zJ7C16Lt1R1pieqAUM9OPWoAFiqu+4qiehfE6euWHEQePK9cqBpFjLMjh4N6u6lgHam93T4BBh5h5GA7CduLULRAX592NSgnTDempR/kke0ctBC9FBs/yEbkaiw=
