language: node_js
node_js:
  - "6"
dist: trusty
sudo: false
addons:
  chrome: stable
install:
- npm install
script:
- npm run storybook
- node_modules/.bin/backstop test
- npm run-script build
deploy:
  provider: npm
  skip_cleanup: true
  email: rafalnowosielski@me.com
  api_key:
    secure: "Pgj5f+iQ4foVi69j5LJk5JZk+15bzyTMeWi3GnOinwaR7Uy/JwiyrKb4jkZd9qxvOohYXOQAlyjuKjfQw+osVFipwu6yJeVAZa9ZeXDFnPKC/i9SYxioUxgdTMkzjxNsXlLVmEYBw2C5Je9HaTVRXDjYgrLBIHrBlBm24nFZkO6nEpeaY0EwM/cfS+HM35zIKWobcj8zE1Bn/NMlOvT+omMMicliET53JFQFne7snxMC2qyioQZ2sOozzh9rlNo62poBaYKzthIJKBOOkHwTtqB7Fh0zJchxoKHuPUwOunz+vu5pEYJCRfOf/ep1udhGW9tdRMoAYTC1LlgkMp0E6yjGEtgUnDfPR5F8pbCJj+fF+AgkLU3lWGoD16cr1kLIgd3Yg3LieGRtf0+5QcirXa6PlSRoLUnI6h1cOX23A5LJaQJGeJ3ZKIxmkB2zzWcBvC6IfBDPrg3YWi1z+b6bc+J+reG7hpPzp/VpRLhyhWJtLxkOagHCCkmoH0ljDeaxDRWjiyoUYULu6xRNjJKLkKeRYn7sJutmU99GQvKuF44uxVeOeOpLmDW3gFfQubGBSw7fAABNOkvBtwYvQWb9MNG88dIERIUWX8gubkVEbZtL+DmcNmJBeHGWnm0wLX5xMtTYdaGAG37W/1OG4a/eEIWs+JEjMyq3Is6v6rUq+98="
  on:
    branch: master
notifications:
  slack:
    secure: "hcLcEUCHCua4mqVMhP1vXIsxaSJ9/u30xGIswPPg9iNdraL6V0CGbO9AUddP+Wpr+UEOxFhqA8aknZ6U0uDFg3Mi5h/IWerLSbFaJzuQtqoVWQuHFVkO4KgCRZy7Ihsk1U3e/JhsZIndmZ7/sMuN47K1naoEvahcbm7FrH8o7rUIFMrmHsGB7yIXtdbVcJINC8Ii5EN95ncGE3zOwVOBd5XMq8RYvxQWDEoyHxewJ3pkYW88Gss9Zjvs3SlOs3cq4jZyaB75DSHIZ1eeZ0A25/RANBdNH8BJcjtg4bMXk6KdG1t/9sn+KuHBU2EOwCIdRCzuuh2JXDA0wXh6oB7HDL484Kgq/rV/slEAVQXULMU/08txtZuf6DFDkVAB2E94SjzIWYUiOgzmbjEDbxs5SyuUJLu3Ciqua3Zpg2nDRQ4mvsOsAKW8CZxOapnM+29LlbNA4H0cfSrajLPwSt9LeWilFvoFvJ9KqfIzYDSxdoZFCMGfTOW9rlPL3zRWRYmn1rlQdCAoh751+wfvIXN5uU9sLWFBGt2jWqor0Lg4XtvFVGWCLtzfI0zh8aaBGihIVtsTCKeIC5mtFj6d83W+T4+WuV4niHnp2Xch9fVMLWThl+XuIDYRhG6cSrN8wmOZR+w6XJELBuzPhJ1qNGKxHJ9J5kgN5f04EUmTCvDmSVg="